"""fourth Migration

Revision ID: 38acb57ebaa4
Revises: ce2df1b30944
Create Date: 2022-05-07 17:48:20.147548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38acb57ebaa4'
down_revision = 'ce2df1b30944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
